### ISSUE TITLE
Korean War Veterans Memorial label gets replaced by Vietnam Veterans Memorial @z18

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#1]
https://github.com/nationalparkservice/park-tiles/issues/136

**Comment by jimmyrocks** [comment]
This was a mistake in WSD_Parks, and the mistake was carried over to CartoDB. 
There was previously no way to update any fields other than the_geom by using CartoDB.
CartoDB now allows you to update the following fields:

```
  poly_geom = ST_Transform(cartodb_parks.wkb_geometry, 3857),
  designation = cartodb_parks.designation,
  name = cartodb_parks.name,
  display_name  = cartodb_parks.display_name,
  display_designation  = cartodb_parks.full_designation,
  display_concatenated  = cartodb_parks.full_name,
  display_state  = cartodb_parks.state,
  display_blurb  = cartodb_parks.blurb,
  poly_source  = cartodb_parks.poly_source,
  display_address  = cartodb_parks.address,
  display_phone  = cartodb_parks.phone,
  display_climate  = cartodb_parks.climate,
  display_url = cartodb_parks.url
```

I updated the data in CartoDB, changed the poly_source to npmap (since the boundary didn't really come from the park), and reran the CartoDB script. It is now updated.
