### ISSUE TITLE
Missing boundary for OKCI

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#243]

**Comment by chadlawlis** [comment]
Site is [here](http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=17.20/-97.51646/35.47296&overlays=park-tiles-overlay).

**Comment by chadlawlis** [comment]
Digging back through email is this message from Eric at IMR from 12/3/15:

> For OKCI, there is no boundary. It has a different designation and the NPS is only involved as an affiliated partner in the management of the site. The only data we have for the site is the point we provided.

This point was previously available here https://github.com/nationalparkservice/places-data/issues/224, but has since been removed from the directory on Drive. I will ping Eric about this again.

I also contacted Melanie Sander, a "Student Park Guide" from 2013.

**Comment by chadlawlis** [comment]
``` sql
insert into parks (unit_id, unit_name_short, unit_name_long, unit_desig_abbr, unit_desig_full, unit_code, unit_region, unit_state, unit_url) values ((select max(unit_id) + 1 from parks), 'Oklahoma City', 'Oklahoma City', 'N MEM', 'National Memorial', 'okci', 'imr', 'ok', 'http://www.nps.gov/okci/index.htm');
insert into parks_poly (unit_id, unit_code) values ((select unit_id from parks where unit_code = 'okci'), 'okci');
insert into parks_line (unit_id, unit_code) values ((select unit_id from parks where unit_code = 'okci'), 'okci');
```

**Comment by chadlawlis** [comment]
From Natasha at the park, 1/13/16:

> Here is the weird answer for you, we don't have any boundaries.  We where de-listed in 2004 and became affiliated with a private partner that now owns the site and operates it.  We only provide the outdoor interpretive first person interpretation.
> We are a weird beast a National Park Service a National site without owning the site.

So, I will add [this point](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbSE55SHh3cHBqM1U) as `geom_point` for OKCI, which will allow us to label the unit, and leave `geom_poly` blank. 

@nateirwin will work on supporting points in the npmap.js geocoder so that it can zoom to this unit without an area geometry.

**Comment by chadlawlis** [comment]
Done.

**Comment by chadlawlis** [comment]
Label should show up here: http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=19.14/-97.51668/35.47295.

**Comment by chadlawlis** [comment]
`geom_point` is now missing. Need to repopulate with [this point](https://drive.google.com/drive/u/0/folders/0B0AXEdn7N9KbSE55SHh3cHBqM1U).

**Comment by chadlawlis** [comment]
Okay, this should be all set.
