### ISSUE TITLE
Error getting bounds when zooming to Katmai KATM from search

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#253]
Searching for and selecting "Katmai National Park & Preserve" in the Park Tiles search bar throws an error, returning the prompt "There was an error getting the bounds for that park."

There is a boundary for KATM in the new boundaries table, so not sure what is going on here.

There is no error when selecting Katmai from the Editor dropdown park list. The error occurs in both PT2 and PT3 beta.

**Comment by chadlawlis** [comment]
Hm, this is strange. I confirmed that the boundary in our CartoDB parks table is accurate, and it is identical to what we have on the server's parks table.

Not only does searching for this unit throw an error on first try, on second try it zooms to the unit but lands at this zoom/extent: http://insidemaps.nps.gov/park-tiles-3/#12/58.6672/-156.5246

![katm_zoom](https://cloud.githubusercontent.com/assets/1238636/12761044/b259d62a-c9a6-11e5-8ae4-d4282a0b0d9f.jpg)

Any ideas here @jimmyrocks @nateirwin?

**Comment by nateirwin** [comment]
Nice catch, @cwlawlis802! Looks like the query to grab the bounding box from CartoDB is failing because the ampersand is not escaped properly. I'm going to switch over to using `cartodb_id` and I'll roll out a new release of NPMap.js with the fix.

In the meantime, I opened an issue for this in the NPMap.js repo (https://github.com/nationalparkservice/npmap.js/issues/312) so I'm going to close this one.

**Comment by chadlawlis** [comment]
Awesome :+1:
