### ISSUE TITLE
Historic Cabins render as hiker shelters in PT 3.0

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#262]
Historic Cabins render as hiker shelters in PT 3.0. A historic building tagged with building:cabin renders as the HFC Hiker Shelter/Cabin in PT 3.0, which is misleading, as historic cabins are generally not available for sleeping.

**Comment by mtaylorlong** [comment]
We've decided to remove POI's entirely from Park Tiles, and instead offer a more customizable POI vector overlay solution. See issues #381 and #380.

The good news related to this issue is that in the vector overlay approach, we can use HFC's cabin symbol to distinguish Historic Cabins from Hiker Shelters.
