### ISSUE TITLE
What happened to BLRI?

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#267]
http://insidemaps.nps.gov/park-tiles-3/#17/35.50735/-83.29468
![image](https://cloud.githubusercontent.com/assets/5861784/11398224/446efa62-934d-11e5-9b14-aca678599664.png)

**Comment by mtaylorlong** [comment]
Hi Tom: Thanks for bringing this up in an issue. We're aware that there are some serious problems with the boundaries here. We're working through the issue, but it gets a little complicated since we have to loop in the Lands database folks to the conversation so we can all be on the same page.

Regarding the BLRI parkway, we had to do some cleanup of old parkway data to make way for a new parkway centerline from the park. You caught me in the middle of the transition, which is why the parkway wasn't there. It's back now. :)

![screen shot 2015-11-30 at 9 25 04 am](https://cloud.githubusercontent.com/assets/4741443/11477265/7034fc6e-9744-11e5-94df-3616c4da7e98.png)
