### ISSUE TITLE
PT3 Feedback for HOFR, VAMA, ELRO and MAVA

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#269]
David Hayes submitted this Park Tiles 3 feedback via email:

> Hello Taylor,
> I worked on the data edits for HOFR, VAMA, ELRO and MAVA. Here are the issues I see:
> HOFR - there are 2 errors on boundary. One where Rt 9 bisects the NPS land. The highway separates NPS parcels, so they should not be shown as continuous over the road.
> The other is a long skinny arm shown sticking out towards Rt 9G which doesn't exist - that's a town highway right-of-way.
> For all, other than the main park visitor contact stations I don't see any of the other point s of interest I entered such as restrooms etc.
> I will send you a graphic with the correct boundary.
> Thanks, Dave Hayes

There are two issues here:
1. HOFR Boundary: We need a better boundary from the park.
2. HOFR, VAMA, ELRO and MAVA POI's: We need to check up on the POI's David entered to see why they're not showing up. Some POI's will not show up in Park Tiles, but Restrooms (the example he gave) should.

@cwlawlis802: Can you look into this? 
I'll get back to David that we're working on it.

**Comment by chadlawlis** [comment]
Sure, I can take care of the boundary. David will have to send us a spatial file, though, otherwise we'll have to default to either our current boundary or Lands (if our current boundary isn't pulling from this already). We avoid customizing geometries in house.

I can take a look at some of the POIs in these parks to make sure they are tagged correctly. Otherwise @mtaylorlong you might want to look into the PT3 rendering to see if most of what he added simply isn't supposed to show up.

**Comment by chadlawlis** [comment]
The HOFR boundary is currently pulling from `WSD_Parks`, which is actually identical to the Lands boundary. So, if David has as custom boundary we can use we can replace the one currently in Places.

**Comment by chadlawlis** [comment]
The POIs added to HOFR look to be nodes tagged only with a name and unit code. One point, for example, is tagged with `{"name":"Restrooms"}` instead of using the restroom preset which would be `{"amenity":"toilets"}`. I am assuming this is similar across all parks he added data to, so I will create issues for each and convert these points to the presets that will translate to Park Tiles.

**Comment by mtaylorlong** [comment]
Nice sleuthing @cwlawlis802. David just sent me new boundary shapefiles for HOFR. It sounds like his data comes from a tax parcel dataset, but the parcels have been merged together where possible. Let's have a look and see if we can use it.

I'll get back to David and let him know that we're working on adding the appropriate tags to the POI's.

**Comment by chadlawlis** [comment]
Great, I'll take a look.

**Comment by chadlawlis** [comment]
The HOFR looks good. The only perceivable issue is the movement of the boundary to the north and east of ELRO no longer being seamlessly adjacent, but fortunately they do not overlap so that shouldn't be a problem (click image to enlarge):

![hofr_boundary](https://cloud.githubusercontent.com/assets/1238636/11479430/369657e0-974f-11e5-8046-1af9caca89c3.jpg)

I can update this in our boundaries table. @jimmyrocks can you re-run boundaries at some point this week?

**Comment by mtaylorlong** [comment]
@cwlawlis802: Will you reply to our email thread with David and include this screenshot? He's adding data for ELRO too, so he likely has boundary data for that park as well.

**Comment by chadlawlis** [comment]
Sure thing, just sent it.

**Comment by chadlawlis** [comment]
All POI translations have been taken care of, along with area to building footprint translations.

I will upload the park boundary now.

**Comment by chadlawlis** [comment]
Refer to the issues referenced above to track each boundary update for HOFR and ELRO.

Otherwise, all set here.
