### ISSUE TITLE
Add three new parks

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#3]
https://github.com/nationalparkservice/park-tiles/issues/133

**Comment by jimmyrocks** [comment]
Is there a source where we can get the boundaries? None of these are in IRMA

**Comment by ryanjhodge** [comment]
@jimmyrocks, @makella 

The IRMA Admin boundaries files were updated with these 3 new parks in late April (TUSK, HONO, and PULL).  The files also contain updates to some existing park boundaries (but I think this issue is covered by #10)

[Centroids - Admin Boundaries 04/2015](https://irma.nps.gov/App/Reference/Profile/2221838)

[Polygons - Admin Boundaries 04/2015](https://irma.nps.gov/App/Reference/Profile/2221839)

**Comment by chadlawlis** [comment]
Looks like TUSK, HONO, and PULL have all been added via the latest Lands release.
