### ISSUE TITLE
Add Area Support for Superclass "Natural Feature"

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#340]
I'm interested in using Natural Feature presets in Editor to add some physical context to our custom mobile basemaps. All the presets in the "Natural Feature" superclass are supported as points, but many of them should also be supported as areas. Rather than pick and choose, I think it would be simpler to update all of them so they can be tagged as points and/or areas.

Wetlands, for example, can be drawn as areas and given a special texture (like we do currently with OSM data). However, if a wetland has a particular name, it's easiest to build this label from a point classified as wetland. Therefore, both point and area should be supported.

I'd like to implement this practice with the FOSC mobile basemap to show grassland and forest as areas. I'm hoping to maintain as many geometries in Places as possible to minimize my use of custom data sources. Custom data sources add complexity to supporting these projects in the future.

@jimmyrocks and @cwlawlis802: Let me know what you think of this as a plan. Step 1 would be to add all the natural feature tags as options when tagging an area in Editor. Step 2 would be making sure they render out as polygons into our polygon vector tiles sources.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
+1

This is something we've been interested in implementing for a little while now. We'll just need to publicize the best practice of adding a point when drawing an area, similar to parking lots.

**Comment by chadlawlis** [comment]
There are currently 47 natural feature presets, all of which are currently supported as points with "Canyon" supported as both a point and line feature:
- Arch
- Arroyo
- Basin
- Bay
- Beach
- Canyon
- Cape
- Cave Entrance
- Cliff
- Desert
- Dune
- Forest
- Fumarole
- Geyser
- Glacier
- Grassland
- Grove
- Harbor
- Hot Spring
- Island
- Isthmus
- Lake
- Lava
- Mountain Pass (Saddle / Gap)
- Mud Pot
- Natural Feature
- Peak
- Pillar
- Plain
- Plateau
- Prairie
- Rapids
- Reef (Bar)
- Ridge
- Rock Formation
- Sea
- Shoal (Bar)
- Spring
- Strait (Channel)
- Stream
- Swamp
- Tree
- Valley
- Volcano
- Waterfall
- Wetland
- Woods

We should probably select a few from this list to support as areas as a start. I'm in favor of Wetland, given GOGA would benefit from this for the mobile basemap. We should be mindful of how far we want to take this, especially hydrological features, given we currently pull this from OpenStreetMap and would otherwise pull from NHD or a related curated dataset.

**Comment by chadlawlis** [comment]
GRTE is interested in adding glaciers as areas - they have the data - so this could be a good initial test case.

**Comment by nateirwin** [comment]
I'd love to see this!

**Comment by chadlawlis** [comment]
Great - these have been added as `{"natural":"glacier"}`.

I'll add a preset to support this - any other natural feature areas of particular use @mtaylorlong @jakecoolidge?

**Comment by chadlawlis** [comment]
See https://github.com/nationalparkservice/places-data/issues/767 for Glacier.

**Comment by chadlawlis** [comment]
@mtaylorlong specify which natural features (that are currently supported) that you would like added as areas and I can generate them.

**Comment by mtaylorlong** [comment]
Here's my quick list:
- Basin
- Beach
- Desert
- Dune
- Forest
- Grassland
- Grove
- Plain
- Plateau
- Prairie
- Reef (Bar)
- Rock Formation
- Shoal (Bar)
- Swamp
- Valley
- Wetland
- Woods

Too much? :wink:

**Comment by chadlawlis** [comment]
Cool, they'll all go live once the presets are regenerated again.

**Comment by chadlawlis** [comment]
Area presets for all types listed here https://github.com/nationalparkservice/places-data/issues/340#issuecomment-237402468 are now available.

**Comment by chadlawlis** [comment]
@mtaylorlong let me know if there are any remaining natural feature types that are currently supported as points that you would like supported as areas. Otherwise, let's close this out.

cc @jakecoolidge - feel free to chime in as well.

**Comment by chadlawlis** [comment]
All set here for now, closing.
