### ISSUE TITLE
Update PARA boundary

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#35]
from Ryan Hodge:
Hi Mamata,

I finally found a published Grand Canyon-Parashant boundary.  Can you add this to Park Tiles?

https://catalog.data.gov/dataset/blm-administrative-unit-boundaries-and-office-locations

In the above dataset, it is this polygon:

![unnamed](https://cloud.githubusercontent.com/assets/1566273/7616924/3e47590e-f965-11e4-9803-aa05ebc9023b.png)

I've also included these examples of how both agencies have styled the NPS-BLM "overlapping" areas (with dotted lines).  
Cartography Examples
[PDF Map on BLM Website](http://www.blm.gov/style/medialib/blm/az/images/parashant.Par.15818.File.dat/parashantmap.pdf)
[NPS Unigrid Brochure Map](http://www.nps.gov/para/index.htm)

**Comment by jimmyrocks** [comment]
We don't have a boundary for PARA from either our internal (WSD Parks) dataset or from the (IRMA/Lands) dataset. It is also not included in 'grca' or 'lake'.

It is also all BLM land, so I'm not sure if it belongs in Park Tiles or not.

Can we find a source for this other than manually digitizing it?

**Comment by ryanjhodge** [comment]
I found a source for the PARA boundary in the BLM administrative boundaries dataset on data.gov (see first link in Mamata's initial post).  The boundary is highlighted in the screenshot.  This polygon will likely overlap a tiny bit with GRCA and LAKE, but it might be the best option right now.

PARA is co-managed as one unit between BLM and NPS.  One of our contacts at PARA had this to say:

> We definitely consider the entire monument as one unit, jointly managed.  If it helps to speak to why we would consider the entire monument for the Park Tiles, NPS funds and management extend across both the NPS and BLM sides of the monument."

There are two areas of PARA that are "historically" NPS (part of LAKE Mead enabling legislation). One of the areas is called gold butte and is the part of the main LAKE boundary that overlaps with PARA.  The second is the Shivwits Plateau, which is the separate polygon within the PARA boundary.  You will see both of these areas in purple _within_ the red PARA boundary on [this map](http://www.blm.gov/style/medialib/blm/az/images/parashant.Par.15818.File.dat/parashantmap.pdf)

Also check out the unigrid map brochure by clicking "View Park Map" on [PARA's NPS webpage](http://www.nps.gov/para/index.htm). You will see that the park map shows the PARA boundary with the Gold Butte and Shivwits Plateau boundaries as dotted lines.

**Comment by ryanjhodge** [comment]
OK, just realized that the data.gov link that I originally provided to Mamata is now 404.  Looks like they took down the geodatabase.  I still have a copy of it, but I just found an alternative on the Arizona BLM GIS site.  

http://www.blm.gov/az/st/en/prog/maps/gis_files.html

Look for the "BLM Field Office Boundaries" (az_fos).  That shapefile contains the PARA boundary.

![capture](https://cloud.githubusercontent.com/assets/4172213/9536467/0a0d53f8-4ce1-11e5-9939-313924344047.PNG)

**Comment by jimmyrocks** [comment]
![image](https://cloud.githubusercontent.com/assets/98192/9590553/a01c94da-4ff2-11e5-9ef7-56b46625caf0.png)
Adding back a part of 'lake' at the request of @ryanjhodge

**Comment by jimmyrocks** [comment]
![image](https://cloud.githubusercontent.com/assets/98192/9591023/c99a3b8e-4ff5-11e5-9705-5ef73c6596c7.png)
PARA Added (in blue)

**Comment by cwlawlis802** [comment]
I will reach out to the PWR regional GIS coordinator to confirm the use of this boundary in Places.

**Comment by chadlawlis** [comment]
This is definitely a complex/political issue, but in its simplest form the issue exists because Lands does not have a boundary for PARA while it does for surrounding units LAKE and GRCA.

I received a custom boundary geometry that PARA uses, [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbcU9RMDNrVTN4UDg) (`para_boundary_20151023.gdb.zip`). From Allen McCoy @ PWR Regional GIS Office:

> It includes:
> - The NPS managed part of the monument
> - A line version of the NPS managed part of the monument to show the lineage
> - The full monument created by merging the BLM's special recreation management areas. This doesn't line up with the NPS data.
> - The special recreation management areas layer.

![qgis 2 10 1-pisa 2015-10-28 14-05-20](https://cloud.githubusercontent.com/assets/1238636/10801459/0f2d0cb2-7d7d-11e5-82e6-77c7b081abbc.jpg)

Our boundaries for LAKE and GRCA overlap exactly along the lines of the NPS managed areas from above, leaving only the BLM special recreation management areas as our PARA boundary in Places:

![qgis 2 10 1-pisa 2015-10-28 14-08-58](https://cloud.githubusercontent.com/assets/1238636/10801577/ac82e75c-7d7d-11e5-8af5-4cb174c20af3.jpg)

Allen also indicated that Lands will not be creating a boundary for this unit, given it is technically not a legislated unit of the NPS. From Sean Carlton, February 2014, forwarded from Allen:

> "Unfortunately PARA is not a legislated unit of the NPS. Therefore, Lands will not be creating a boundary for PARA. However, there is a management boundary standard being developed that could include PARA"

**So, given Lands represents the NPS managed areas as LAKE and GRCA, our best way forward is probably to leave as is.** The Lands "management boundary standard" being developed could help re-address this, down the road.
