### ISSUE TITLE
Add symbol name as POI attribute in Mapbox Tiles

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#351]
In an effort to support more POI types while keeping our CartoCSS slim, we want to write symbol names into our POI vector tiles as an attribute named `symbol`.

@jimmyrocks: How soon can you work this into the rendering for POI's? I'm guessing the best place to store this info is in the NPS_Preset_Classes spreadsheet, but let me know if there's a better place. I'd like to be able to adjust as needed and know that my changes will be implemented automatically on the next POI update. Is that possible?

Regarding naming, I'm going to use the base name for our symbols in NPMap symbol library. Example: For the Visitor Center preset, I'm assigning the symbol name `visitor-center` without appending `-black` or `-white-32.svg`. This way, I can append the appropriate suffix to designate color and size as needed in each style.

**Comment by jimmyrocks** [comment]
This method won't allow for it frequent changes to the tags or their attributes (such as icon name). This is because we assign the presets as soon as the item is contributed and cache that information. There is a script that can be run on demand to update all presets that have changed, but this script takes about 60 minutes to complete.

I do have an idea that would speed this process up substantially. Instead of reading the tags and converting them into a preset, we can just do a matching of presets to icons at the last step when the vector tiles get rendered. This would mean that CartoDB would not be able to contain the icon names.

Just the thought of updating every changed object in CartoDB with the new icon seems a little tedious to me though. So we can talk more about this process.

If you do just want to tag matched for vector tiles and are not concerned about getting the icon name into CartoDB, there will also be a fairly quick turn around on this, as it's a much easier process.

**Comment by nateirwin** [comment]
Unfortunately, I think we'll want the symbol name in CartoDB as well. That way we can pull it from there for the vector rendering approach.

**Comment by mtaylorlong** [comment]
Yeah. I wish we could just implement the simpler approach for PT3, but we need to demo that overlay approach soon, so I agree with Nate that the names need to be in cartodb. This just means we'll need to be a little more thoughtful about how we implement this and make updates. 

I can work up a final list and deliver it tomorrow. If I need to make any changes, we can do another update in a couple weeks. Does that sound okay to you guys?

**Comment by jimmyrocks** [comment]
I would prefer to keep it in the same workflow as the presets in CartoDB
for simplicity, but it would come at the cost of the ability to rapidly
change icons.

Although, since vector tiles are only run once a day, we would only need to
change icons, at most, once a day.

We may be able to run the update script overnight (it may take up to 90
minutes) every day until we decide that we are solid with the icons.

This update script is current only run on demand.

**Comment by jimmyrocks** [comment]
For reference, this is the current update script:

``` sql
SELECT
  o2p_render_element(nps_render_point.osm_id, 'N')
FROM
 nps_render_point
WHERE
  o2p_get_preset(nps_render_point.tags, ARRAY['point'::text])::json->>'superclass' != nps_render_point.superclass OR
  o2p_get_preset(nps_render_point.tags, ARRAY['point'::text])::json->>'class' != nps_render_point.class OR
  o2p_get_preset(nps_render_point.tags, ARRAY['point'::text])::json->>'type' != nps_render_point.type
UNION ALL
SELECT
  o2p_render_element(nps_render_line.osm_id, CASE WHEN osm_id > 0 THEN 'W' ELSE 'R' END)
FROM
 nps_render_line
WHERE
  o2p_get_preset(nps_render_line.tags, ARRAY['line'::text])::json->>'superclass' != nps_render_line.superclass OR
  o2p_get_preset(nps_render_line.tags, ARRAY['line'::text])::json->>'class' != nps_render_line.class OR
  o2p_get_preset(nps_render_line.tags, ARRAY['line'::text])::json->>'type' != nps_render_line.type
UNION ALL
SELECT
  o2p_render_element(nps_render_polygon.osm_id, CASE WHEN osm_id > 0 THEN 'W' ELSE 'R' END)
FROM
 nps_render_polygon
WHERE
  o2p_get_preset(nps_render_polygon.tags, ARRAY['line'::text])::json->>'superclass' != nps_render_polygon.superclass OR
  o2p_get_preset(nps_render_polygon.tags, ARRAY['line'::text])::json->>'class' != nps_render_polygon.class OR
  o2p_get_preset(nps_render_polygon.tags, ARRAY['line'::text])::json->>'type' != nps_render_polygon.type;
```

**Comment by mtaylorlong** [comment]
This one's no longer a need for our mapbox tiles since we're handling it with POI vector overlay now. #380.
