### ISSUE TITLE
DEWA "Joseph M. McDade Recreational Trail - Hiking, Biking, XC Skiing" label

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#391]
From Katherine @ DEWA, 11/30/15:

> The Joseph M McDade Trail does not appear to be labeled at any scale and is a 32 mile premier trail for our park.

Shorten to "Joseph M. McDade Recreational Trail", "Joseph M. McDade Trail" or "McDade Trail" - the longest one that we can render in Park Tiles.

**Comment by chadlawlis** [comment]
@mtaylorlong I can fix this in JOSM, just relying on you to know/figure out which label will successfully render.

**Comment by mtaylorlong** [comment]
I haven't made this fix yet, because if they are having wipe out their places data to replace it with theirs, the change will have to happen in their data. 

However, It's such a quick fix, that we should probably just make the change now. @cwlawlis802: It would be great if you could do it through JOSM. Let's try using "Joseph M. McDade Trail". Note that there are multiple line segments, so you'll have to grab them all my name and change them in bulk.

If we do start using their data as is, we'll just want to remind them that they'll need some kind of label attribute to handle this properly in the future.

**Comment by chadlawlis** [comment]
We're only altering the trail name - the geometry is already in place and should be accurate - so this doesn't require any further seeding/slashing and burning.

I'll update the trail name to "Joseph M. McDade Trail", accounting for (and merging, if appropriate) all trail segments, and we can go from there.

**Comment by chadlawlis** [comment]
Okay, this should be all set.

I merged the connecting segments of the trail and renamed to "Joseph M. McDade Trail".

JOSM filters:
`type:node` [x] E [ ] I
`type:way` [x] E [x] I
`highway:path` [x] E [x] I
`name="Joseph M. McDade Trail"` [x] E [x] I

@mtaylorlong confirm that this name renders in PT3 once the tiles are regenerated.

**Comment by mtaylorlong** [comment]
The Joseph M. McDade Trail label is rendering beautifully! Case closed!

<img width="588" alt="screen shot 2016-01-26 at 6 06 56 pm" src="https://cloud.githubusercontent.com/assets/4741443/12601072/7947868e-c45b-11e5-9fb8-a06a468167e2.png">
