### ISSUE TITLE
Parks Table Points Moved to Oklahoma

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#395]
I pulled in park labeling points from our `parks` table last night, and the majority of parks seem to have been moved to one single location in Oklahoma. I could be messing something up, but I'm pretty sure I'm not. In any case, it shouldn't be too hard to get things back to normal. Let's tackle this on Monday.

cc: @cwlawlis802, @jimmyrocks

**Comment by chadlawlis** [comment]
@jimmyrocks did the digging here :+1:, discovering a command from `2016-01-13 16:43:12.349215-07`: `update parks set geom_point = (select wkb_geometry from okci)`.

Since then, the `geom_point` for only JOFI and DABE were updated. So, all other `geom_point` records were reverted to the transaction before `21829` (the OKCI command) via the following:

``` sql
UPDATE
  "parks"
SET
  "geom_point" = (
    SELECT "row_data"->'geom_point'
    FROM "audit"."logged_actions"
    WHERE
      "transaction_id" = '21829' AND
      ("row_data"->'unit_id')::smallint = "parks"."unit_id"
  )
WHERE
  "parks"."unit_id" NOT IN (
    SELECT ("row_data"->'unit_id')::smallint
    FROM audit.logged_actions
    WHERE
      "transaction_id" > '21829' AND
      "changed_fields" ? 'geom_point'
  );
```

DABE (https://github.com/nationalparkservice/places-data/issues/370) was also projected in 4326 (WGS84), which was reprojected to 3857. All `geom_points` records should be in good shape now.

**Comment by jimmyrocks** [comment]
``` sql
UPDATE parks
SET geom_point = ST_Transform(ST_SetSRID(geom_point, 4326), 3857)
WHERE unit_code = 'dabe';
```

**Comment by mtaylorlong** [comment]
Thanks guys!
