### ISSUE TITLE
Visitor Center vs. Ranger Station

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#41]
In writing up the tracing guide I am having a hard time differentiating between a visitor center and a ranger station. The names seem to be [interchangeable to some parks](http://www.nps.gov/calo/planyourvisit/visitorcenters.htm), while the [VC](http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dinformation) and [ranger station](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dranger_station) OSM wikis don't seem to clear things up either.

At present, I have the following language describing a VC:

> A visitor center is a building housing information for visitors, typically including some or all of the following: information resources, facilities (e.g. restrooms, drinking water), ranger staff, and exhibits.

Any thoughts on how these should be differentiated @tpcolson @asouthwould @jimmyrocks @nateirwin?

**Comment by tpcolson** [comment]
Your text for a VC is spot on. A Ranger station serves a specific function in the NPS, which is different from the FS...it is a building or facility PRIMARILY intended to house LE and rescue staff, and is typically not open to the public (unlike a FS ranger station). Many VC's and other park facilities may be located in the same building as a Ranger Station, or Vice-Versa, or a "Ranger Station" may simply be a ranger sitting at a desk at a CG Kiosk. 

IMHO, given the law enforcement and medical function of a ranger station, Ranger Stations that are co-located with VC's need to have their own icon, offset from the VC icon. We direct visitors to Ranger Stations for medical emergencies, not VC's.....

**Comment by makella** [comment]
Another option might be to come up with a VC icon that indicates there are
RS functions there... if that makes sense.  But I agree, it is important to
show.

**Comment by asouthwould** [comment]
I don't believe any of our parks with formal/traditional visitor centers are co-located with a ranger station. However in a couple remote AK parks, the main ranger station is also considered the visitor center, even though I think the term is used loosely as they do not provide the same services typically associated with visitor centers. In that case, it may be more appropriate to display the ranger station plus information symbols rather than visitor center symbol. This will be a discussion to have with each of our parks individually. Also, most of our ranger stations are in the backcountry and only seasonally open. However, when they are open, I believe they also sometimes serve for visitor information, public use, and emergency shelter.

This brings up an interesting thought. When we have these instances where a single place serves multiple functions, is it appropriate to create multiple coincident points where each one has a different type? I can envision the structured data for those individual services being unique so I don't think we would want a single point trying to capture all that information. Does that make sense?

**Comment by jakecoolidge** [comment]
By necessity, we are limited cartographically in terms of how many different POI types we can represent at a single point. If a VC, Ranger Station, store, and restrooms are all located in a small cluster of buildings in close proximity, only the VC will be visible at most scales until the user zooms in to a large scale, since we currently place an emphasis on displaying VCs over other POIs. Even if we decided to favor Ranger Stations over VCs, the symbols would either draw on top of each other (and be illegible), or the RS symbol would obscure all others at that location.

Printed maps in the parks have typically not been constrained by this; certain key locations may have five or seven pictographs associated with them. There's a danger of the printed map becoming cluttered, but it has the advantage of clarifying the range of amenities and services available at a particular location. 

I wonder if we can quantify, across the Service, how often the one-symbol-per-location model will obscure information on our maps? In other words, how many of these places house multiple functions, and how important is it to represent these separate functions? Visitor Center symbols can stand in for a lot of key amenities and services, so I think it's a good idea to make sure they're well-represented on public-facing maps. The only potential limitation is what Tom brought up--how important is it to also represent those first-responder functions (like Ranger Stations) that Visitor Centers don't provide? 

To follow what Mamata mentioned, if we determined that we had a significant number of locations where a Ranger Station is located in close proximity to a Visitor Center, but we need to represent both simultaneously at all scales, we might consider a new "symbol" that is actually just the VC symbol and the Ranger Station symbol placed side-by-side. I wouldn't extend this loophole to the entire set, but we could justify implementing a side-by-side icon in order to assure Ranger Station locations are not obscured. It would also require creating point locations that are tagged, essentially, "Visitor Center AND Ranger Station". We're thinking of other locations that could display differently based on scale--a campground that dissolves into individual campsites at zoom ~19, for example, or an area with multiple restroom buildings represented by one restroom symbol at smaller scales.

**Comment by chadlawlis** [comment]
Thanks for the input everyone, you each bring up really valuable perspectives. I think Jake brings up an important point about visual hierarchy and the unavoidable consequence of obscuring information on the map, as is the case with the co-location of numerous amenities. This is also the beauty of tagging, however, in its ability to represent a variety of information associated with a specific point. Obviously the limitation comes in how many different symbols we can make visible on a given point at varying scales.

For now, the most feasible solution seems to be to create multiple coincident points for a location housing both a VC and RS, which it sounds like we are all on the same page on. @jakecoolidge and @makella will then be able to determine the visual hierarchy, and eventually a combined VC/RS symbol could come into play.

Regarding the description, thanks @tpcolson for the insight:

> ...it is a building or facility PRIMARILY intended to house LE and rescue staff, and is typically not open to the public ... [or] may simply be a ranger sitting at a desk at a CG Kiosk ...We direct visitors to Ranger Stations for medical emergencies, not VC's

I will stitch this together for a simple description in the tracing guide. Thanks again everyone!
