### ISSUE TITLE
Improve "view" interface so it more accurately reflects the Places database

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#46]
Hey guys,  Per the conversation we had on the telecon today, here are some screen grabs of the visualization issue I had brought up.  When in Places Editor viewer mode, only some of the POIs are coming up.  You have to switch to the Editor mode for all the POIs in Places to be revealed.  This replicates the discrepancies I was seeing between the links to the "new data in places" viewers.  Thanks! H

![places tiles](https://cloud.githubusercontent.com/assets/11545684/8016155/11c16b8c-0b9d-11e5-9964-a4e6451d320b.JPG)

![places editor](https://cloud.githubusercontent.com/assets/11545684/8016157/142f2ec2-0b9d-11e5-8e7b-41f8053be496.JPG)

![overview](https://cloud.githubusercontent.com/assets/11545684/8016158/15dd9542-0b9d-11e5-9d63-334081407e89.JPG)

**Comment by heidiogle** [comment]
So, any one want to address this?

**Comment by makella** [comment]
Hi Heidi,

@jakecoolidge and I discussed this yesterday.  Sorry for the late reply!  What I suggest we do is create a POI overlay that symbolizes all of the features in the Places database and have that overlaid on Park Tiles when viewing the map in the Places editor.

We'll work on this as soon as we can and update you with progress here. 

Thanks for pointing this out, I agree that it is a good idea and that's why I brought it up with Jake to look into.

mamata

**Comment by heidiogle** [comment]
Sounds great, Mamata.  Thanks!

**Comment by jakecoolidge** [comment]
Jimmy's updates to Places Editor with a view-mode map based on Places data I designed addresses this issue.

**Comment by jimmyrocks** [comment]
Yeah, i think this can be closed now, thanks for the new view mode and also
thanks to Jake's new maps
