### ISSUE TITLE
Support park boundaries for offshore/submarine areas

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#47]
This is an email from Justin Mills (justin_s_mills@nps.gov):

Of WAPA's ca. 2000 acres, half are water/ocean/coral reef.  These are clipped off of NPMap (but are an essential part of the park).  The same applies to KAHO and a couple of other coastal parks I looked at.  I know it's cartographically tricky, but these areas are really important to the parks.  We really struggle to effectively communicate to the public that WAPA is half water, and that water is under NPS administrative jurisdiction.

WAPA Unigrid w/ map: http://www.nps.gov/wapa/planyourvisit/upload/WAPA-unigrid-brochure.pdf
WAPA in NPMap: http://insidemaps.nps.gov/places/view/#15/13.4739/144.7140

KAHO brochure with boundary map:  http://www.nps.gov/kaho/planyourvisit/loader.cfm?csModule=security/getfile&PageID=124426
KAHO in NPMap: http://insidemaps.nps.gov/places/view/#14/19.6732/-156.0433

**Comment by makella** [comment]
I've been thinking about this a lot lately (especially with my Mobile work at NPNH) and what is happening is that since we have our park polygons under the water (so waterbodies show up in parks), complete park boundaries that are not cut out in Mapbox's water layer get covered up like this.  

Parks like Isle Royale and Sleeping Bear Dunes are actually cut out of the water polygons so that's why they show up -- but you'll notice that the park boundary line is not showing.

Other places like the islands in Jamaica Bay do not show up at all (lines and/or polygons) because they are no islands cut out of the water to support those features.

There are a couple of options:  
- We add another park boundary layer in the layer order (nps_park_boundary.line) and symbolize that so at least the park boundary line shows on top of the water.  
  - The problem with this is that if there are waterbodies inside of a park, we could see the park boundary drawing through the waterbody (which might not be the end of the world.)
  - The other problem with this approach is that any land will not show up (because we can't put the polygons over the water) so we'll only see the lines (which also might not be the end of the world).
- We have a tag in the data that flags whether a park is coastal, in a waterbody (like the Great Lakes, etc.) and do the same as mentioned above (with figuring out layering) and symbolize those parks the same except with different layer ordering.

**Comment by makella** [comment]
Also referencing this in Park Tiles because once we figure out if and what data work needs to be done, we'll have to implement in the Park Tiles style sheets.

**Comment by makella** [comment]
I'll write Justin when Park Tiles 3 is published

**Comment by mtaylorlong** [comment]
I think we've solved this one, so I'm closing it.
