### ISSUE TITLE
OBRI (OBED) boundary not rendering

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#531]
Current landing view in PT3:

![obri](https://cloud.githubusercontent.com/assets/1238636/12987033/82c4850a-d0b7-11e5-8c51-88588d154267.jpg)

`min_zoom_poly` currently set to Z14, which seems a little high (zoomed in), but regardless this is not rendering at any scale - only the point and label.

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks runs the tiles to Mapbox.

**Comment by mtaylorlong** [comment]
The boundary is showing up now at z14, but we need to update the carto fields so that it shows up sooner. Also, there seems to be a strange issue with the tiling where the boundary disappears along a tile edge. Next time we update the boundaries, we'll see if this mystery resolves itself on its own. Otherwise, we'll have to investigate further.

**Comment by chadlawlis** [comment]
This has been resolved.
