### ISSUE TITLE
Add "capacity" to trail/trailhead?

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#67]
From @jakecoolidge:

> SEKI has a quota system on certain trailheads during peak season (for example, a particular trail allows up to 15 hikers per day). is this an instance where I could associate "capacity" with a trailhead? Or would "access=15" be acceptable here?

**Comment by jimmyrocks** [comment]
access=15 is _not_ acceptable, since the access tag is used for private/permissive/etc.

I think the capacity tag is fine to use here. I agree it may be confusing to tag the trailhead as such, but that's probably the best place for it.

**Comment by tpcolson** [comment]
Hmmmm...ummmmm....GRSM has no opinion: We don't enforce capacity....

**Comment by jakecoolidge** [comment]
Based on discussion during the Places Team meeting Friday 7/17, we decided it's better to link these sorts of details to features in Places through structured data. Trail quotas can change from year to year, and it would be best for park employees to update this info regularly on their end, rather than managing it in Places.
