### ISSUE TITLE
Deletes in Places not getting sent out to CartoDB

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#70]
I deleted a duplicate point for "Craig Thomas Discovery and Visitor Center" in GRTE last Saturday, but the change never got pushed out to CartoDB. You can see here that there is only one point in Places: 

http://insidemaps.nps.gov/places/edit/#background=mapbox-satellite&map=20.00/-110.71839/43.65333&overlays=park-tiles-overlay

And running this query returns both points from CartoDB:

https://nps.cartodb.com/api/v2/sql?q=SELECT%20points_of_interest.cartodb_id,points_of_interest.name,parks.full_name,parks.unit_code,st_y(points_of_interest.the_geom)%20as%20lat,st_x(points_of_interest.the_geom)%20as%20lng,%20points_of_interest.type%20FROM%20points_of_interest,parks%20WHERE%20points_of_interest.unit_code=parks.unit_code%20AND%20points_of_interest.name%20IS%20NOT%20NULL%20AND%20points_of_interest.name%20ilike%20%27%25craig%20thomas%25%27%20ORDER%20BY%20points_of_interest.name,parks.full_name

**Comment by jimmyrocks** [comment]
This should be fixed by this commit:
https://github.com/nationalparkservice/cron-tasks/commit/afe3b0a4b05747feed5d233cd742beaafcca9212

The cartodb cleanup was done with these two commands in pgs and cartodb respectively:
`SELECT osm_id, n.id FROM (VALUES (...),(all cartodb_ids in cartodb),(...) ) n (id) LEFT JOIN nps_render_(point/line/polygon) ON nps_render_(point/line/polygon).osm_id = n.id WHERE osm_id is null;`

`DELETE FROM places_polygons where cartodb_id in (values from the result of that previous query)`
