### ISSUE TITLE
Move CLBA + GLEC labels

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#745]
Per @rangernathan's request:

> Labels for Glen Echo and Clara Barton should be clarified. The buildings that are in Glen Echo are not showing in green; I've circled them below. Clara Barton is tucked in that southwest corner of the park.

![clba_glec_labels](https://cloud.githubusercontent.com/assets/1238636/16499811/2a42e7c0-3ebf-11e6-9b41-38895728aa86.png)

**Comment by chadlawlis** [comment]
See also https://github.com/nationalparkservice/places-data/issues/364#issuecomment-194994778 for GLEC label shift.

**Comment by chadlawlis** [comment]
Done via:

``` sql
-- clba
BEGIN;
UPDATE parks_label
SET geom_label = (SELECT ST_GeomFromText('POINT(-77.14074432849883 38.96750487449427)', 4326))
WHERE label_id = 197;

UPDATE parks_label
SET geom_label = ST_Transform(ST_SetSRID(geom_label, 4326), 3857)
WHERE label_id = 197;
COMMIT;

-- glec
BEGIN;
UPDATE parks_label
SET geom_label = (SELECT ST_GeomFromText('POINT(-77.13879168033598 38.96585736966923)', 4326))
WHERE label_id = 333;

UPDATE parks_label
SET geom_label = ST_Transform(ST_SetSRID(geom_label, 4326), 3857)
WHERE label_id = 333;
COMMIT;
```

These will go live once the boundaries have been regenerated, likely tomorrow.

**Comment by chadlawlis** [comment]
Oops, didn't actually run this code yesterday - just ran it now. Changes will appear as follows:

![clba_glec_label_moves](https://cloud.githubusercontent.com/assets/1238636/16526103/d4acdce0-3f6c-11e6-8c2d-752a0777dab8.png)

**Comment by chadlawlis** [comment]
The label move is all set.

I have updated GLEC's `min_zoom_label` to 13 instead of 12, as it was knocking out the CLBA label at 12.

However, the CLBA label also appears to be getting knocked out at z14, though I am not sure why. @mtaylorlong would you take a look?

**Comment by mtaylorlong** [comment]
All the park labels without enforced label directions are set to `shield-avoid-edges: true;`. This means that CLBE's label disappears at z14 because doesn't have anywhere else to go but off the tile edge, so it disappears. 

In cases like this, the next option is setting enforced label directions for GLEC and CLBE in directions that will work for all zoom levels. These two seem to be in a tough location, but after playing with it, I hard-coded their directions for N and S labels, and it seems to work ok without them disappearing. Next time we run the tiles, you can review the changes for final approval.

**Comment by chadlawlis** [comment]
Thanks @mtaylorlong. I ran the tiles earlier this afternoon, we'll see if it caught this change. If not I'll run again later this week.

**Comment by chadlawlis** [comment]
All set here.
