### ISSUE TITLE
Rendering order of buildings and parking lots in nps_places_polygons

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#76]
I think that parking lots are drawing on top of buildings in the nps_places_polygons data source from Mapbox Studio. Is it possible to check the upload source to see if buildings are on top?

![screen shot 2015-07-10 at 2 41 40 pm](https://cloud.githubusercontent.com/assets/1566273/8628655/21086434-2712-11e5-8bf5-95e83417716b.png)

**Comment by jimmyrocks** [comment]
Ordering based on tags was proposed as something we could add to the master spreadsheet in the JSON Matchscore column. Currently all the tags have an identical display order, so the field needs to be updated in the master spreadsheet.

I am tagging this task as a schema task since the change that is needed is in the schema.

**Comment by chadlawlis** [comment]
@jimmyrocks this should be all set - building has layerIndex of 70 while parking has layerIndex of 10.
