### ISSUE TITLE
Closed facilities not tagged

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#82]
There is no "tag" for closed facilities that are in places. Example, GRSM has restrooms that are in campgrounds that are seasonally closed, or closed due to budget. The facilities still exist, and should not be deleted from the database. When , for example, https://nps.cartodb.com/api/v2/sql?filename=NPS_POIS&format=geojson&q=SELECT%20*%20FROM%20points_of_interest%20WHERE%20unit_code=%27grsm%27%20and%20type%20=%20%27Restroom%27 is added to a builder map, it shows these closed facilities.

**Comment by chadlawlis** [comment]
We are considering using the `{"access":"*"}` tag for closed or publicly inaccessible features, still TBD. This requires further discussion with @jimmyrocks along with the larger Places team (this is a concern/request from others as well).

**Comment by chadlawlis** [comment]
Tom, 

Follow some of our logic on this topic here: https://github.com/nationalparkservice/places-data/issues/183.

We are using the "access" key for this. Features are automatically tagged `{"access":"yes"}` unless specified otherwise. For now, all values other than "yes" will be lumped into `{"access":"no"}` but we will maintain all raw tags. So, if you have a specific use case for `{"access":"private"}` feel free to add this, but again be aware that in Park Tiles this will likely be rendered as simply not accessible/closed.
