### ISSUE TITLE
VALR boundary

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#88]
From @ryanjhodge

There are no boundaries for VALR in Hawaii. There is a label for it. A visitor center shows up in the water at zoom level 17 (This might have to do with bullet point 5 below)

**Comment by jimmyrocks** [comment]
This is strange, because there is a boundary for it in our dataset. I'll need to look into it with @jakecoolidge and @mtaylorlong 

Our Boundary:
![image](https://cloud.githubusercontent.com/assets/98192/9482302/ee238078-4b4f-11e5-858d-297351c28755.png)

As far as the Visitors Center, this can be moved in Places

**Comment by jakecoolidge** [comment]
I brought the data source into Mapbox. Although I see the boundary in CartoDB, the boundary fails to appear in Mapbox, even at large-scale zooms. We haven't applied any particular cartocss to VALR. The next thing I'd like to do is look at the tm2source directly, but I haven't gotten there yet. At this point, the boundary appears not to have gotten into the tm2source.

**Comment by jimmyrocks** [comment]
tm2source
![image](https://cloud.githubusercontent.com/assets/98192/9583478/cf1e0400-4fc8-11e5-9f50-b41308b871dc.png)

Park Tiles
![image](https://cloud.githubusercontent.com/assets/98192/9583511/fa616ba2-4fc8-11e5-83ad-d84de59efdd8.png)

VALR is in the tm2source and in Park Tiles, we've been using the Lands Boundary for this, so maybe it was updated there?

**Comment by chadlawlis** [comment]
Note: updated with latest Land Resources Division boundary.
