### ISSUE TITLE
ADA Tagging

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#93]
Request from GRSM Leadership: We'd rather not be showing POI's in Builder maps unless there is an ADA Accessible "Tag" that the park can use to symbolize or otherwise report what is ADA compatible. Looking in OSM wiki, this doesn't seem obvious. Can you add a ADA "Tag" that is blank so parks can go in and tag "yes" or "no"?

**Comment by nateirwin** [comment]
Humm... there's got to be a standard way of doing this in OpenStreetMap, right?

**Comment by jimmyrocks** [comment]
There is nothing in OpenStreetMap to denote if something is legally ADA
accessible, although wheelchair tags within the US are supposed to
correlate with ADA accessibility.
http://wiki.openstreetmap.org/wiki/Key:wheelchair

The problem is that ADA accessibility is a legal definition, so it should
not be something managed by volunteers.

**Comment by tpcolson** [comment]
Based on https://github.com/nationalparkservice/places-editor/issues/75, the hope and assumption is that only qualified people will be editing park data in places. ADA compliance is a legal definition, and mis-tagging an item with it can have costly consequences. We have many restrooms that have the "hand rails", but since they haven't been through the expensive review and certification process, we can't call them ADA-accessible. GRSM rule is that the status must be first reflected in FMSS before a GIS object will get the "Tag". 

I like, and thus propose, http://wiki.openstreetmap.org/wiki/Key:wheelchair as the tag to be used in places when an object has been declared ADA-accessible and is being edited by a park-approved editor.

**Comment by tpcolson** [comment]
This was already documented in https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272.

**Comment by jimmyrocks** [comment]
If the wheelchair tag makes sense for your uses, then it's easy because it's already in our list.

The comment about volunteers adding the data was meant to describe why OpenStreetMap doesn't support a specific ADA tag.

As far as validation of who can put data into places, we should reference this issue:
https://github.com/nationalparkservice/places-editor/issues/75
